don/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('web.urls')),
    path('api/', include('don_api.urls')),
]

if settings.DEBUG:
    urlpatterns += [
        path('admin/', admin.site.urls),
        path("__debug__/", include("debug_toolbar.urls")),
    ]

web/urls.py
from django.conf import settings
from django.urls import path
from django.views import defaults as default_views
from django.views.generic.base import RedirectView

from .views.api import (
    APIListView, APIDetailView, APISpecificationView, APIAddView, APIAddSuccessView, APIValidatorReportsView
)
from .views.content import APIDesignRulesView
from .views.contact import ContactView, ContactSuccessView
from .views.generic import TemplateView
from .views.index import IndexView
from .views.organization import OrganizationDetailView
from .views.repository import RepositoryListView
from .views.statistics import StatisticsView


app_name = "web"


urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("apis", APIListView.as_view(), name="api_list"),
    path("apis/toevoegen", APIAddView.as_view(), name="api_add"),
    path("apis/toevoegen/succes", APIAddSuccessView.as_view(), name="api_add_success"),
    path("apis/<slug:api_id>", APIDetailView.as_view(), name="api_detail"),
    path("apis/<slug:api_id>/score-details", APIValidatorReportsView.as_view(), name="api_validator_reports"),
    path("apis/<slug:api_id>/specificatie/<str:environment_name>", APISpecificationView.as_view(),
         name="api_specification"),
    path("organisaties/<slug:slug>", OrganizationDetailView.as_view(), name="organization_detail"),
    path("repositorys", RepositoryListView.as_view(), name="repository_list"),
    path("statistieken", StatisticsView.as_view(), name="statistics"),
    path("api-design-rules", APIDesignRulesView.as_view(), name="content_api_design_rules"),
    path("contact", ContactView.as_view(), name="contact"),
    path("contact/succes", ContactSuccessView.as_view(), name="contact_success"),
    path("over", TemplateView.as_view(title="Over Developer Overheid", template_name="content/about.html"),
         name="content_about"),
    path("privacy", TemplateView.as_view(title="Privacyverklaring", template_name="content/privacy.html"),
         name="content_privacy"),
    path("api-rules", RedirectView.as_view(pattern_name="web:content_api_design_rules", permanent=True)),
    path(".well-known/security.txt", RedirectView.as_view(url="https://www.ncsc.nl/.well-known/security.txt")),
]


if settings.DEBUG:
    urlpatterns += [
        path("error/400", default_views.bad_request, {"exception": Exception("Bad request")}),
        path("error/404", default_views.page_not_found, {"exception": Exception("Page not Found")}),
        path("error/500", default_views.server_error),
    ]

web/templates/layouts/base.html
{% load static %}<!DOCTYPE html>
<html lang="nl">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="Description" content="Eén centrale plek voor de developer die voor of met de overheid ontwikkelt">
        <meta name="theme-color" content="#095070">
        <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}">
        <link rel="stylesheet" href="{% static 'dist/main.css' %}">
        <title>{% if title %}{{ title }} - {% endif %}Developer Overheid</title>
        {% block head %}{% endblock %}
        {% if GOATCOUNTER_ENABLED %}<script async src="//dongeitjes.commondatafactory.nl/count.js" data-goatcounter="https://dongeitjes.commondatafactory.nl/count"></script>{% endif %}
    </head>
    <body>
        <a href="#hoofdinhoud" class="skip-to-content">Naar hoofdinhoud</a>
        <header class="header">
            <div class="header__top">
                <nav class="container">
                    <ul class="header__top__nav-list" aria-label="Gerelateerde websites">
                        <li class="header__top__nav-list__li active">
                            <a href="/" aria-current="page">Developer</a>
                        </li>
                        <li class="header__top__nav-list__li">
                            <a href="https://forum.developer.overheid.nl">Forum</a>
                        </li>
                        <li class="header__top__nav-list__li">
                            <a href="https://gitlab.com/commonground/don/developer.overheid.nl" target="_blank"
                                rel="noopener noreferrer">
                                <svg width="24" height="24" viewBox="0 0 24 24">
                                    <path fill="none" d="M0 0h24v24H0z"></path>
                                    <path
                                        d="M5.68 7.314l-1.82 5.914L12 19.442l8.14-6.214-1.82-5.914L16.643 11H7.356L5.681 7.314zM15.357 9l2.888-6.354a.4.4 0 0 1 .747.048l3.367 10.945a.5.5 0 0 1-.174.544L12 21.958 1.816 14.183a.5.5 0 0 1-.174-.544L5.009 2.694a.4.4 0 0 1 .747-.048L8.644 9h6.712z"
                                        fill="#fff"></path>
                                </svg>
                                GitLab
                            </a>
                        </li>
                    </ul>
                </nav>
            </div>
            <nav class="container header__nav">
                <a class="header__nav__logo" href="{% url 'web:index' %}"
                    {% if request.resolver_match.view_name == "web:index" %} aria-current="page"{% endif %}>
                    Developer.overheid.nl
                </a>
                <ul aria-label="Website navigatie" class="header__nav__links">
                    <li>
                        <a href="{% url 'web:api_list' %}"
                            {% if 'web:api_' in request.resolver_match.view_name %} class="active" {% endif %}
                            {% if request.resolver_match.view_name == 'web:api_list' %} aria-current="page" {% endif %}>
                            API's
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'web:repository_list' %}"
                            {% if 'web:repository_' in request.resolver_match.view_name %} class="active" {% endif %}
                            {% if request.resolver_match.view_name == 'web:repository_list'  %} aria-current="page" {% endif %}>
                            Repository's
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'web:content_api_design_rules' %}"
                            {% if request.resolver_match.view_name == 'web:content_api_design_rules' %} class="active" aria-current="page"{% endif %}>
                            API&nbsp;Design&nbsp;Rules
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'web:content_about' %}"
                            {% if request.resolver_match.view_name == 'web:content_about' %} class="active" resolver_match{% endif %}>
                            Over
                        </a>
                    </li>
                </ul>
            </nav>
        </header>
        <div class="{% if request.resolver_match.view_name == 'web:index' %}{% else %}container mt-lg mb-xxl{% endif %}">
            {% if breadcrumbs %}
            {% include "partials/breadcrumb.html" %}
            {% endif %}
            <div id="hoofdinhoud">
                {% block content %}{% endblock %}
            </div>
        </div>
        <section class="pre-footer">
            <div class="container">
                <div class="py-xl">
                    <h3 class="pre-footer__heading">Wensen of feedback?</h3>
                    <p>
                        Deze website is 'permanent beta' en zal worden aangepast naar de behoeften van gebruikers.
                        <br>
                            Wensen en opmerkingen kunnen via een melding op GitLab doorgegeven worden.
                    </p>
                    <div class="pre-footer__buttons">
                        <a href="https://gitlab.com/commonground/don/developer.overheid.nl/-/issues/new" class="button button--primary"
                            target="_blank" rel="noopener noreferrer">
                            <svg class="button__icon button__icon--first" width="16" height="16" viewBox="0 0 24 24">
                                <path fill="none" d="M0 0h24v24H0z"></path>
                                <path fill="#ffffff"
                                    d="M5.68 7.314l-1.82 5.914L12 19.442l8.14-6.214-1.82-5.914L16.643 11H7.356L5.681 7.314zM15.357 9l2.888-6.354a.4.4 0 0 1 .747.048l3.367 10.945a.5.5 0 0 1-.174.544L12 21.958 1.816 14.183a.5.5 0 0 1-.174-.544L5.009 2.694a.4.4 0 0 1 .747-.048L8.644 9h6.712z">
                                </path>
                            </svg>
                            Melding maken op GitLab
                            <svg class="button__icon button__icon--last" width="16" height="16" viewBox="0 0 24 24">
                                <path fill="none" d="M0 0h24v24H0z"></path>
                                <path
                                    d="M10 6v2H5v11h11v-5h2v6a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V7a1 1 0 0 1 1-1h6zm11-3v8h-2V6.413l-7.793 7.794-1.414-1.414L17.585 5H13V3h8z"
                                    fill="#ffffff"></path>
                            </svg>
                        </a>
                        <p class="mb-0 mr-4 ml-4">Of</p>
                        <a href="{% url 'web:contact' %}" class="button">
                            Neem contact op
                        </a>
                    </div>
                </div>
            </div>
        </section>
        <footer class="footer">
            <div class="footer__content container py-xl">
                <div class="footer__content__logos">
                    <div class="footer__content__logos__text mb-6">Een initiatief van:</div>
                    <div class="footer__content__logos__images">
                        <img src="{% static 'images/logo-bzk.png' %}" width="276"
                            alt="Logo van Ministerie van Binnenlandse Zaken en Koninkrijksrelaties">
                        <img src="{% static 'images/logo-vng.svg' %}" width="101"
                            alt="Logo van Vereniging van Nederlandse Gemeenten">
                    </div>
                </div>
                <div class="footer__content__links">
                    <div class="footer__content__links__top">
                        <a class="footer__content__links__link--start" href="{% url 'web:content_privacy' %}"
                            {% if request.resolver_match.view_name == 'web:content_privacy' %} aria-current="page" {% endif %}>
                            Privacyverklaring
                        </a>
                        <a class="footer__content__links__link--start" href="{% url 'web:statistics' %}"
                            {% if request.resolver_match.view_name == 'web:statistics' %} aria-current="page" {% endif %}>
                            Statistieken
                        </a>
                        <a class="footer__content__links__link--start" href="{% url 'web:contact' %}"
                            {% if request.resolver_match.view_name == 'web:contact' %} aria-current="page" {% endif %}>
                            Contact
                        </a>
                    </div>
                    <div class="footer__content__links__bottom">
                        <a class="footer__content__links__link--end"  href="https://haven.commonground.nl" target="_blank" rel="noopener noreferrer">Powered by Haven</a>
                    </div>
                </div>
            </div>
            {% include "partials/mobile_navigation.html" %}
        </footer>
        <script src="{% static 'dist/main.js' %}" defer></script>
        {% block tail %}{% endblock %}
    </body>
</html>