don/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('web.urls')),
    path('api/', include('don_api.urls')),
]

if settings.DEBUG:
    urlpatterns += [
        path('admin/', admin.site.urls),
        path("__debug__/", include("debug_toolbar.urls")),
    ]

web/urls.py
from django.conf import settings
from django.urls import path
from django.views import defaults as default_views
from django.views.generic.base import RedirectView

from .views.api import (
    APIListView, APIDetailView, APISpecificationView, APIAddView, APIAddSuccessView, APIValidatorReportsView
)
from .views.content import APIDesignRulesView
from .views.contact import ContactView, ContactSuccessView
from .views.generic import TemplateView
from .views.index import IndexView
from .views.organization import OrganizationDetailView
from .views.repository import RepositoryListView
from .views.statistics import StatisticsView


app_name = "web"


urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("apis", APIListView.as_view(), name="api_list"),
    path("apis/toevoegen", APIAddView.as_view(), name="api_add"),
    path("apis/toevoegen/succes", APIAddSuccessView.as_view(), name="api_add_success"),
    path("apis/<slug:api_id>", APIDetailView.as_view(), name="api_detail"),
    path("apis/<slug:api_id>/score-details", APIValidatorReportsView.as_view(), name="api_validator_reports"),
    path("apis/<slug:api_id>/specificatie/<str:environment_name>", APISpecificationView.as_view(),
         name="api_specification"),
    path("organisaties/<slug:slug>", OrganizationDetailView.as_view(), name="organization_detail"),
    path("repositorys", RepositoryListView.as_view(), name="repository_list"),
    path("statistieken", StatisticsView.as_view(), name="statistics"),
    path("api-design-rules", APIDesignRulesView.as_view(), name="content_api_design_rules"),
    path("contact", ContactView.as_view(), name="contact"),
    path("contact/succes", ContactSuccessView.as_view(), name="contact_success"),
    path("over", TemplateView.as_view(title="Over Developer Overheid", template_name="content/about.html"),
         name="content_about"),
    path("privacy", TemplateView.as_view(title="Privacyverklaring", template_name="content/privacy.html"),
         name="content_privacy"),
    path("api-rules", RedirectView.as_view(pattern_name="web:content_api_design_rules", permanent=True)),
    path(".well-known/security.txt", RedirectView.as_view(url="https://www.ncsc.nl/.well-known/security.txt")),
]


if settings.DEBUG:
    urlpatterns += [
        path("error/400", default_views.bad_request, {"exception": Exception("Bad request")}),
        path("error/404", default_views.page_not_found, {"exception": Exception("Page not Found")}),
        path("error/500", default_views.server_error),
    ]

core/models/api.py
from typing import NamedTuple

from django.db import models
from django.urls import reverse
from django.utils.functional import cached_property
from django.utils.translation import gettext_lazy as _

from . import MAX_ENUM_LENGTH, MAX_TEXT_LENGTH, MAX_URL_LENGTH

from .organization import Organization
from .topic import Topic
from .validator import ForeignValidatorReport, BaseValidatorReport, ValidatorReportsMixin


class API(ValidatorReportsMixin["APIValidatorReport"], models.Model):
    class APIType(models.TextChoices):
        UNKNOWN = 'unknown', 'Onbekend'
        ODATA = 'odata', 'OData'
        REST_JSON = 'rest_json', 'REST/JSON'
        REST_XML = 'rest_xml', 'REST/XML'
        SOAP_XML = 'soap_xml', 'SOAP/XML'
        GRPC = 'grpc', 'gRPC'
        GRAPHQL = 'graphql', 'GraphQL'
        SPARQL = 'sparql', 'SPARQL'
        WFS = 'wfs', 'WFS'
        WMS = 'wms', 'WMS'

    class APIAuthentication(models.TextChoices):
        UNKNOWN = 'unknown', 'Unknown'
        NONE = 'none', 'None'
        MUTUAL_TLS = 'mutual_tls', 'Mutal TLS'
        API_KEY = 'api_key', 'API key'
        IP_ALLOW_LIST = 'ip_allow_list', 'IP allow list'
        OAUTH2 = "oauth2", "OAuth 2.0"

    api_id = models.CharField(max_length=MAX_TEXT_LENGTH, unique=True)
    description = models.TextField()
    organization = models.ForeignKey(
        Organization, verbose_name=_("organization"), on_delete=models.PROTECT)
    service_name = models.CharField(max_length=MAX_TEXT_LENGTH)
    api_type = models.CharField(
        max_length=MAX_ENUM_LENGTH,
        choices=APIType.choices,
        default=APIType.UNKNOWN
    )
    api_authentication = models.CharField(
        max_length=MAX_ENUM_LENGTH,
        choices=APIAuthentication.choices,
        default=APIAuthentication.UNKNOWN
    )
    is_reference_implementation = models.BooleanField(default=False)

    contact_email = models.CharField(max_length=MAX_TEXT_LENGTH, blank=True)
    contact_phone = models.CharField(max_length=MAX_TEXT_LENGTH, blank=True)
    contact_url = models.URLField(max_length=MAX_URL_LENGTH, blank=True)

    terms_government_only = models.BooleanField(null=True)
    terms_pay_per_use = models.BooleanField(null=True)
    terms_uptime_guarantee = models.DecimalField(
        null=True,
        decimal_places=6,
        max_digits=8,
    )
    terms_support_response_time = models.PositiveIntegerField(
        help_text='Measured in number of workdays',
        null=True,
    )

    forum_vendor = models.CharField(max_length=MAX_ENUM_LENGTH, blank=True)
    forum_url = models.URLField(max_length=MAX_URL_LENGTH, blank=True)

    badges = models.ManyToManyField(
        'Badge',
        through='APIBadge',
        related_name='apis',
    )
    referenced_apis = models.ManyToManyField(
        'self',
        through='Relation',
        symmetrical=False,
        related_name='referenced_by_apis',
    )
    topics = models.ManyToManyField(Topic)

    def __str__(self):
        return self.api_id

    def get_absolute_url(self):
        return reverse("web:api_detail", kwargs={"api_id": self.api_id})

    def get_production_environment(self):
        return self.environments.filter(name=Environment.EnvironmentType.PRODUCTION).first()

    ADR_TESTABLE_TYPES = (APIType.REST_JSON.ODATA, APIType.REST_JSON, APIType.REST_XML)
    """API's of these types can be tested on API Design Rules"""

    def is_adr_testable(self):
        return self.api_type in self.ADR_TESTABLE_TYPES

    class BasicScore(NamedTuple):
        has_documentation: bool
        has_specification: bool
        has_contact_details: bool
        provides_sla: bool

    @cached_property
    def basic_api_score(self) -> "BasicScore":
        production_environment = self.get_production_environment()

        return self.BasicScore(
            has_documentation=(production_environment and production_environment.documentation_url != ""),
            has_specification=(production_environment and production_environment.specification_url != ""),
            has_contact_details=(self.contact_email != "" or self.contact_phone != "" or self.contact_url != ""),
            provides_sla=(self.terms_support_response_time is not None and self.terms_uptime_guarantee >= 0.9)
        )

    class Meta:
        verbose_name = _("API")
        verbose_name_plural = _("APIs")


class Environment(models.Model):
    class EnvironmentType(models.TextChoices):
        PRODUCTION = 'production', 'Production'
        ACCEPTANCE = 'acceptance', 'Acceptance'
        TEST = 'test', 'Test'
        DEMO = 'demo', 'Demo'

    name = models.CharField(max_length=MAX_ENUM_LENGTH, choices=EnvironmentType.choices)
    api_url = models.URLField(max_length=MAX_URL_LENGTH)
    specification_url = models.URLField(max_length=MAX_URL_LENGTH, blank=True)
    documentation_url = models.URLField(max_length=MAX_URL_LENGTH, blank=True)

    api = models.ForeignKey(
        API,
        to_field='api_id',
        on_delete=models.CASCADE,
        related_name='environments',
    )

    def __str__(self):
        return f"{self.name} - {self.api_url}"


class Relation(models.Model):
    TYPE_REFERENCE_IMPLEMENTATION = "reference-implementation"

    name = models.CharField(max_length=MAX_TEXT_LENGTH, blank=True)
    from_api = models.ForeignKey(
        API,
        to_field='api_id',
        on_delete=models.CASCADE,
        related_name='relations_from',
    )
    to_api = models.ForeignKey(
        API,
        to_field='api_id',
        on_delete=models.PROTECT,
        related_name='relations_to',
    )

    def __str__(self):
        return f'{self.from_api_id} {self.name} {self.to_api_id}'


class APIValidatorReport(BaseValidatorReport):
    api = ForeignValidatorReport(API)

core/models/topic.py
from django.db import models

from . import MAX_TEXT_LENGTH


class Topic(models.Model):
    name = models.CharField(max_length=MAX_TEXT_LENGTH, unique=True)

    def __str__(self):
        return self.name

web/templates/partials/api_item.html
{% load don_extras %}
<li>
    <a href="{% url 'web:api_detail' api_id=api.api_id %}" class="api-item">
        <div class="api-item__left">
            <h4 class="api-item__left__title mb-3">{{ api.service_name }}</h4>
            <sub class="api-item__left__subtitle mb-4">{{ api.organization.name }}</sub>
            {% if api.description %}
            <p class="api-item__left__description">{{ api.description | truncatewords:42 }}</p>
            {% endif %}

            {% if api.topics.all %}
            <div class="mt-4">
                {% include "partials/topic_list.html" with topics=api.topics.all %}
            </div>
            {% endif %}
        </div>
        <div class="api-item__right">
            <div class="api-item__right__category pill pill--white pill--sm">
                {{ api.get_api_type_display }}
            </div>
            {% if api.latest_validator_reports.count %}
            <div class="api-item__right__grade">
                {% for validator_report in api.latest_validator_reports %}
                {% score_pie validator_report.report is_large=False %}
                {% endfor %}
            </div>
            {% endif %}
        </div>
    </a>
</li>

web/templates/partials/api_list_results.html
<div class="filters">{% include "partials/facet_filters.html" %}</div>
<div class="results">
    <div class="results__header">
        {% if paginator.count %}<span class="results-count filter-hx-indicator">{{ paginator.count }} API{{ paginator.count | pluralize:"'s" }}</span>{% endif %}
        <a href="{% url 'web:api_add' %}" class="button button--add-icon">API toevoegen</a>
    </div>
    <div class="filter-hx-indicator filter-spinner mb-04">
        <div class="spinner"></div>
    </div>
    {% if paginator.count %}
        <ul class="results__list item-list item-list--shadow filter-hx-indicator">
            {% for api in object_list %}
                {% include "partials/api_item.html" with api=api %}
            {% endfor %}
        </ul>
        {% include "partials/paginator.html" %}
    {% else %}
        Geen API's gevonden.
    {% endif %}
</div>

web/templates/partials/breadcrumb.html
<nav class="breadcrumb" aria-label="Breadcrumb">
    <ul>
        <li>
            <a href="{% url 'web:index' %}">Home</a>
        </li>
        {% for breadcrumb in breadcrumbs %}
        {% if forloop.last %}
        <li>
            <a aria-current="page" href="{{ breadcrumb.url }}">{{ breadcrumb.title }}</a>
        </li>
        {% else %}
        <li>
            {% if breadcrumb.url %}
            <a href="{{ breadcrumb.url }}">{{ breadcrumb.title }}</a>
            {% else %}
            <span>{{ breadcrumb.title }}</span>
            {% endif %}
        </li>
        {% endif %}
        {% endfor %}
    </ul>
</nav>

web/templates/partials/external_link.html
{% load static %}
<a href="{{ href }}" target="_blank" rel="noopener noreferrer">{{ title }}<img src="{% static 'images/icons/external-link.svg' %}" width="16" height="16" alt=""></a>

web/templates/partials/facet_filters.html
<form class="facet-filters"
      action="{{ request.path_info }}"
      hx-boost="true"
      hx-target="#list-results"
      hx-trigger="submit, change delay:500ms"
      hx-indicator=".filter-hx-indicator">
    <div class="facet-filters__query">
        <label for="query">{{ search_label }}</label>
        <div class="search-field">
            <input id="query"
                   type="search"
                   name="q"
                   value="{{ form.search_text }}"
                   placeholder="Voer een zoekterm in">
            <svg viewBox="0 0 12 12">
                <path d="M8.576 7.547h-.542l-.192-.185A4.44 4.44 0 0 0 8.92 4.46a4.46 4.46 0 1 0-4.46 4.46 4.44 4.44 0 0 0 2.903-1.078l.185.192v.542L10.977 12 12 10.978l-3.424-3.43zm-4.116 0A3.083 3.083 0 0 1 1.372 4.46 3.083 3.083 0 0 1 4.46 1.372 3.083 3.083 0 0 1 7.547 4.46 3.083 3.083 0 0 1 4.46 7.547z" fill="#757575" fill-rule="nonzero">
                </path>
            </svg>
            {% if form.topic %}
            <div class="facet-filters__query__topic">
                <input name="thema" value="{{ form.topic }}" type="hidden">
                <a href="{{ request.path_info }}{{ form.topic_remove_query }}" class="pill pill--white pill--clickable pill--lg">{{ form.topic }} <span class="pill__close">&#x2715</span></a>
            </div>
            {% endif %}
        </div>
        <button class="button facet-filters__filter-toggle js-click-to-toggle"
                aria-expanded="false"
                data-label-target-hidden="Verberg filters"
                data-label-target-shown="Toon filters"
                aria-controls="js-filters"
                type="button">Toon filters</button>
    </div>

    <div id="js-filters" class="facet-filters-wrapper">
        <ul class="facet-filters__list">
            {% for field_name, field in form.fields.items %}
                <li>
                    <h3 class="facet-filters__list__heading">{{ field.label }}</h3>
                    {% for option in field.options %}
                        <div class="facet-filters__list__option"
                             {% if not option.count %}aria-disabled="true"{% endif %}>
                            <input id="{{ field_name }}_{{ option.value }}"
                                   name="{{ field_name }}"
                                   value="{{ option.value }}"
                                   type="checkbox"
                                   {% if option.selected and option.count %}checked{% endif %}
                                   {% if not option.count %}disabled{% endif %}>
                            <label for="{{ field_name }}_{{ option.value }}">
                                {{ option.label }} <small>({{ option.count }})</small>
                            </label>
                        </div>
                    {% endfor %}
                </li>
            {% endfor %}
        </ul>
        <button type="submit" class="button mt-4 w-100">Filter</button>
    </div>
</form>

web/templates/partials/mobile_navigation.html
{% load static don_extras %}
<div id="wrapper" class="mobile-navigation">
    <div class="mobile-navigation__backdrop mobile-navigation-close-on-click" id="mobile-navigation-backdrop"></div>
    <div role="dialog"
         aria-label="Subnavigatie"
         id="mobile-navigation-drawer"
         class="mobile-navigation__drawer">
        <div class="mobile-navigation__drawer__header">
            <button type="button"
                    title="Navigatie sluiten"
                    class="mobile-navigation__drawer__header__close-btn mobile-navigation-close-on-click">
            </button>
        </div>
        <ul class="mobile-navigation__drawer__navigation">
            <li>
                <a href="{% url 'web:content_api_design_rules' %}"{% if request.resolver_match.view_name == 'web:content_api_design_rules' %} class="active"{% endif %}>API Design Rules
                    <img src="{% static 'images/icons/chevron-right.svg' %}" width="16" height="16" alt="">
                </a>
            </li>
            <li>
                <a href="{% url 'web:statistics' %}"{% if request.resolver_match.view_name == 'web:statistics' %} class="active"{% endif %}>Statistieken
                    <img src="{% static 'images/icons/chevron-right.svg' %}" width="16" height="16" alt="">
                </a>
            </li>
            <li>
                <a href="{% url 'web:content_about' %}"{% if request.resolver_match.view_name == 'web:content_about' %} class="active"{% endif %}>Over
                    <img src="{% static 'images/icons/chevron-right.svg' %}" width="16" height="16" alt="">
                </a>
            </li>
        </ul>
    </div>
    <nav class="mobile-navigation__navigation" aria-label="Hoofdnavigatie">
        <a href="{% url 'web:index' %}" class="mobile-navigation__navigation__button{% if request.resolver_match.view_name == 'web:index' %} active{% endif %}" >
            <span>Home</span>
            <svg width="24" height="24" viewBox="0 0 24 24">
                <path d="M19,21 L5,21 C4.44771525,21 4,20.5522847 4,20 L4,11 L1,11 L11.327,1.612 C11.7085185,1.26485664 12.2914815,1.26485664 12.673,1.612 L23,11 L20,11 L20,20 C20,20.5522847 19.5522847,21 19,21 Z M6,19 L18,19 L18,9.157 L12,3.703 L6,9.157 L6,19 Z" fill="#757575" fill-rule="nonzero"></path>
            </svg>
        </a>
        <a href="{% url 'web:api_list' %}" class="mobile-navigation__navigation__button{% if 'web:api_' in request.resolver_match.view_name %} active{% endif %}">
            <span>API's</span>
            <svg width="24" height="24" viewBox="0 0 24 24">
                <path d="M15,1.9999938 C16.4293537,1.9999938 17.7501755,2.76237671 18.4647473,4.00029394 C19.1793191,5.23821118 19.1790342,6.76334979 18.464,8.001 L23,7.9999938 L23,9.9999938 L21,9.9999938 L21,19.9999938 C21,20.5522847 20.5522847,20.9999938 20,20.9999938 L4,20.9999938 C3.44771525,20.9999938 3,20.5522847 3,19.9999938 L3,9.9999938 L1,9.9999938 L1,7.9999938 L5.536,8.001 C4.50816088,6.22118917 4.99641446,3.95208799 6.6653342,2.75255193 C8.33425394,1.55301586 10.6406303,1.81347679 12,3.355 C12.7578482,2.49189847 13.8514035,1.997976 15,1.9999938 Z M11,10 L5,10 L5,19 L11,19 L11,10 Z M19,10 L13,10 L13,19 L19,19 L19,10 Z M9,3.99997958 C7.92117082,3.99517218 7.03293687,4.84685865 6.99245826,5.92493898 C6.95197965,7.00301931 7.77384631,7.91891482 8.85,7.995 L9,8 L11,8 L11,6 C11.0000422,5.0123981 10.2792023,4.17262169 9.303,4.023 L9.149,4.005 L9,3.99997958 Z M15,3.9999999 C13.9533752,3.99966878 13.0834968,4.80632296 13.005,5.85 L13,5.9999999 L13,7.9999999 L15,7.9999999 C16.0466248,8.00033122 16.9165032,7.19367704 16.995,6.15 L17,5.9999999 C17,4.8954305 16.1045695,3.9999999 15,3.9999999 Z" fill="#757575" fill-rule="nonzero"></path>
            </svg>
        </a>
        <a href="{% url 'web:repository_list' %}" class="mobile-navigation__navigation__button{% if request.resolver_match.view_name == 'web:repository_list' %} active{% endif %}">
            <span>Repository's</span>
            <svg width="24" height="24" viewBox="0 0 24 24">
                <path fill="rgb(117, 117, 117)" d="M24 12l-5.657 5.657-1.414-1.414L21.172 12l-4.243-4.243 1.414-1.414L24 12zM2.828 12l4.243 4.243-1.414 1.414L0 12l5.657-5.657L7.07 7.757 2.828 12zm6.96 9H7.66l6.552-18h2.128L9.788 21z"></path>
            </svg>
        </a>
        <button type="button"
                id="mobile-navigation-toggle"
                class="mobile-navigation__navigation__button{% ifmatchview web:statistics web:content_api_design_rules web:content_about %} active{% endifmatchview %}"
                aria-expanded="false"
                aria-controls="mobile-navigation-drawer">
            <span>Meer</span>
            <img src="{% static 'images/icons/dots.svg' %}" width="24" height="24" alt="">
        </button>
    </nav>
</div>

web/templates/partials/paginator.html
<nav aria-label="Paginering" class="pagination filter-hx-indicator">
    <ul class="pagination__list" hx-boost="true" hx-target="#list-results">
        <li>
            {% if page_obj.has_previous %}
                <a href="?{{ page_kwarg }}={{ page_obj.previous_page_number }}{{ filter_query }}"
                   class="pagination__list__link"
                   aria-label="Vorige pagina">«</a>
            {% else %}
                <a class="pagination__list__link" aria-label="Vorige pagina">«</a>
            {% endif %}
        </li>
        {% for page_number in page_range %}
            <li>
                {% if page_number == page_obj.paginator.ELLIPSIS %}
                    <a class="pagination__list__spacer">{{ page_number }}</a>
                {% else %}
                    <a href="?{{ page_kwarg }}={{ page_number }}{{ filter_query }}"
                       class="pagination__list__link"
                       aria-label="Pagina {{ page_number }}"
                       {% if page_number == page_obj.number %}aria-current="page"{% endif %}>{{ page_number }}</a>
                {% endif %}
            </li>
        {% endfor %}
        <li>
            {% if page_obj.has_next %}
                <a href="?{{ page_kwarg }}={{ page_obj.next_page_number }}{{ filter_query }}"
                   class="pagination__list__link"
                   aria-label="Volgende pagina">»</a>
            {% else %}
                <a class="pagination__list__link" aria-label="Volgende pagina">»</a>
            {% endif %}
        </li>
    </ul>
</nav>

web/templates/partials/repository_item.html
{% load static i18n don_extras %}
<li class="repository-item">
    <div class="repository-item__header">
        {% if repository.archived %}
        <p class="repository-item__header__archived">
            Deze repository is <span title="Gearchiveerde repository's worden niet langer onderhouden.">gearchiveerd</span>
        </p>
        {% endif %}
    </div>
    <div class="repository-item__body">
        <div class="repository-item__body__avatar">
            {% if repository.avatar_url %}
            <img src="{{ repository.avatar_url }}" alt="Avatar van {{ repository.name }}"/>
            {% else %}
            <img src="{% static 'images/repository-placeholder.svg' %}" alt=""/>
            {% endif %}
        </div>
        <div class="repository-item__body__info">
            <div class="repository-item__body__info__path mb-3">
                <a href="{{ repository.url }}" target="_blank" rel="noopener noreferrer">{{ owner_name }} / <span class="repository-item__body__info__path__repository">{{ repository.name }}</span></a>
            </div>
            <a href="{{ repository.organization.get_absolute_url }}" class="repository-item__body__info__organization mb-4">{{ repository.organization.name }}</a>
            {% if repository.description %}
            <div class="repository-item__body__info__description mb-4">
                {{ repository.description }}
            </div>
            {% else %}
            <div class="repository-item__body__info__description mb-4">
                <i>Geen beschrijving ingevuld</i>
            </div>
            {% endif %}
            {% if repository.topics.all %}
            <ul class="repository-item__body__info__topics topic-list mb-2">
                {% for name in repository.topics.all %}
                <li>
                    <a href="{{ request.path_info }}?thema={{ name }}" class="topic-pill pill--clickable">{{ name }}</a>
                </li>
                {% endfor %}
            </ul>
            {% endif %}
            <div class="repository-item__body__info__details">
                {% if repository.main_programming_language or stars_url or forks_url or issues_url %}
                <div class="repository-item__body__info__details__left">
                    {% if repository.main_programming_language %}
                    <div class="repository-item__body__info__details__left__lang">
                        <span class="repository-item__body__info__details__left__lang__dot" style="background:{{ repository.main_programming_language.color }}"></span>
                        {{ repository.main_programming_language }}
                    </div>
                    {% endif %}
                    {% if stars_url %}
                    <a href="{{ stars_url }}" class="repository-item__body__info__details__left__prop" target="_blank" rel="noopener noreferrer">
                        {{ repository.stars }}
                        <svg width="20" height="20" viewBox="0 0 24 24">
                            <path fill="none" d="M0 0h24v24H0z"></path>
                            <path d="M12 18.26l-7.053 3.948 1.575-7.928L.587 8.792l8.027-.952L12 .5l3.386 7.34 8.027.952-5.935 5.488 1.575 7.928L12 18.26zm0-2.292l4.247 2.377-.949-4.773 3.573-3.305-4.833-.573L12 5.275l-2.038 4.42-4.833.572 3.573 3.305-.949 4.773L12 15.968z"></path>
                        </svg>
                    </a>
                    {% endif %}
                    {% if forks_url %}
                    <a href="{{ forks_url }}" class="repository-item__body__info__details__left__prop" target="_blank" rel="noopener noreferrer">
                        {{ repository.fork_count }}
                        <svg width="20" height="20" viewBox="0 0 24 24">
                            <path fill="none" d="M0 0h24v24H0z"></path>
                            <path d="M7.105 15.21A3.001 3.001 0 1 1 5 15.17V8.83a3.001 3.001 0 1 1 2 0V12c.836-.628 1.874-1 3-1h4a3.001 3.001 0 0 0 2.895-2.21 3.001 3.001 0 1 1 2.032.064A5.001 5.001 0 0 1 14 13h-4a3.001 3.001 0 0 0-2.895 2.21zM6 17a1 1 0 1 0 0 2 1 1 0 0 0 0-2zM6 5a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm12 0a1 1 0 1 0 0 2 1 1 0 0 0 0-2z"></path>
                        </svg>
                    </a>
                    {% endif %}
                    {% if issues_url %}
                    <a href="{{ issues_url }}" class="repository-item__body__info__details__left__prop" target="_blank" rel="noopener noreferrer">
                        {{ repository.issue_open_count }}
                        <svg width="20" height="20" viewBox="0 0 24 24">
                            <path fill="none" d="M0 0h24v24H0z"></path>
                            <path d="M12 20a8 8 0 1 0 0-16 8 8 0 0 0 0 16zm0 2C6.477 22 2 17.523 2 12S6.477 2 12 2s10 4.477 10 10-4.477 10-10 10zm0-8a2 2 0 1 1 0-4 2 2 0 0 1 0 4z"></path>
                        </svg>
                    </a>
                    {% endif %}
                    {% if merge_requests_url %}
                    <a href="{{ merge_requests_url }}" class="repository-item__body__info__details__left__prop" target="_blank" rel="noopener noreferrer">
                        {{ repository.merge_request_open_count }}
                        <svg width="20" height="20" viewBox="0 0 24 24">
                            <path fill="none" d="M0 0h24v24H0z"></path>
                            <path d="M15 5h2a2 2 0 0 1 2 2v8.17a3.001 3.001 0 1 1-2 0V7h-2v3l-4.5-4L15 2v3zM5 8.83a3.001 3.001 0 1 1 2 0v6.34a3.001 3.001 0 1 1-2 0V8.83zM6 7a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm0 12a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm12 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2z"></path>
                        </svg>
                    </a>
                    {% endif %}
                </div>
                {% endif %}
                <div class="repository-item__body__info__details__timestamp">
                    <svg width="20" height="20" viewBox="0 0 24 24">
                        <path fill="none" d="M0 0H24V24H0z"></path>
                        <path d="M12 2c5.523 0 10 4.477 10 10s-4.477 10-10 10S2 17.523 2 12h2c0 4.418 3.582 8 8 8s8-3.582 8-8-3.582-8-8-8C9.25 4 6.824 5.387 5.385 7.5H8v2H2v-6h2V6c1.824-2.43 4.729-4 8-4zm1 5v4.585l3.243 3.243-1.415 1.415L11 12.413V7h2z"></path>
                    </svg>{% language "nl" %}{{ repository.last_change | don_naturaltime }}{% endlanguage %} bijgewerkt
                </div>
            </div>
        </div>
    </div>
</li>

web/templates/partials/topic_list.html
<ul class="topic-list">
    {% for topic in topics %}
    <li class="topic-pill">{{ topic }}</li>
    {% endfor %}
</ul>