don/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('web.urls')),
    path('api/', include('don_api.urls')),
]

if settings.DEBUG:
    urlpatterns += [
        path('admin/', admin.site.urls),
        path("__debug__/", include("debug_toolbar.urls")),
    ]

web/urls.py
from django.conf import settings
from django.urls import path
from django.views import defaults as default_views
from django.views.generic.base import RedirectView

from .views.api import (
    APIListView, APIDetailView, APISpecificationView, APIAddView, APIAddSuccessView, APIValidatorReportsView
)
from .views.content import APIDesignRulesView
from .views.contact import ContactView, ContactSuccessView
from .views.generic import TemplateView
from .views.index import IndexView
from .views.organization import OrganizationDetailView
from .views.repository import RepositoryListView
from .views.statistics import StatisticsView


app_name = "web"


urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("apis", APIListView.as_view(), name="api_list"),
    path("apis/toevoegen", APIAddView.as_view(), name="api_add"),
    path("apis/toevoegen/succes", APIAddSuccessView.as_view(), name="api_add_success"),
    path("apis/<slug:api_id>", APIDetailView.as_view(), name="api_detail"),
    path("apis/<slug:api_id>/score-details", APIValidatorReportsView.as_view(), name="api_validator_reports"),
    path("apis/<slug:api_id>/specificatie/<str:environment_name>", APISpecificationView.as_view(),
         name="api_specification"),
    path("organisaties/<slug:slug>", OrganizationDetailView.as_view(), name="organization_detail"),
    path("repositorys", RepositoryListView.as_view(), name="repository_list"),
    path("statistieken", StatisticsView.as_view(), name="statistics"),
    path("api-design-rules", APIDesignRulesView.as_view(), name="content_api_design_rules"),
    path("contact", ContactView.as_view(), name="contact"),
    path("contact/succes", ContactSuccessView.as_view(), name="contact_success"),
    path("over", TemplateView.as_view(title="Over Developer Overheid", template_name="content/about.html"),
         name="content_about"),
    path("privacy", TemplateView.as_view(title="Privacyverklaring", template_name="content/privacy.html"),
         name="content_privacy"),
    path("api-rules", RedirectView.as_view(pattern_name="web:content_api_design_rules", permanent=True)),
    path(".well-known/security.txt", RedirectView.as_view(url="https://www.ncsc.nl/.well-known/security.txt")),
]


if settings.DEBUG:
    urlpatterns += [
        path("error/400", default_views.bad_request, {"exception": Exception("Bad request")}),
        path("error/404", default_views.page_not_found, {"exception": Exception("Page not Found")}),
        path("error/500", default_views.server_error),
    ]

core/models/api.py
from typing import NamedTuple

from django.db import models
from django.urls import reverse
from django.utils.functional import cached_property
from django.utils.translation import gettext_lazy as _

from . import MAX_ENUM_LENGTH, MAX_TEXT_LENGTH, MAX_URL_LENGTH

from .organization import Organization
from .topic import Topic
from .validator import ForeignValidatorReport, BaseValidatorReport, ValidatorReportsMixin


class API(ValidatorReportsMixin["APIValidatorReport"], models.Model):
    class APIType(models.TextChoices):
        UNKNOWN = 'unknown', 'Onbekend'
        ODATA = 'odata', 'OData'
        REST_JSON = 'rest_json', 'REST/JSON'
        REST_XML = 'rest_xml', 'REST/XML'
        SOAP_XML = 'soap_xml', 'SOAP/XML'
        GRPC = 'grpc', 'gRPC'
        GRAPHQL = 'graphql', 'GraphQL'
        SPARQL = 'sparql', 'SPARQL'
        WFS = 'wfs', 'WFS'
        WMS = 'wms', 'WMS'

    class APIAuthentication(models.TextChoices):
        UNKNOWN = 'unknown', 'Unknown'
        NONE = 'none', 'None'
        MUTUAL_TLS = 'mutual_tls', 'Mutal TLS'
        API_KEY = 'api_key', 'API key'
        IP_ALLOW_LIST = 'ip_allow_list', 'IP allow list'
        OAUTH2 = "oauth2", "OAuth 2.0"

    api_id = models.CharField(max_length=MAX_TEXT_LENGTH, unique=True)
    description = models.TextField()
    organization = models.ForeignKey(
        Organization, verbose_name=_("organization"), on_delete=models.PROTECT)
    service_name = models.CharField(max_length=MAX_TEXT_LENGTH)
    api_type = models.CharField(
        max_length=MAX_ENUM_LENGTH,
        choices=APIType.choices,
        default=APIType.UNKNOWN
    )
    api_authentication = models.CharField(
        max_length=MAX_ENUM_LENGTH,
        choices=APIAuthentication.choices,
        default=APIAuthentication.UNKNOWN
    )
    is_reference_implementation = models.BooleanField(default=False)

    contact_email = models.CharField(max_length=MAX_TEXT_LENGTH, blank=True)
    contact_phone = models.CharField(max_length=MAX_TEXT_LENGTH, blank=True)
    contact_url = models.URLField(max_length=MAX_URL_LENGTH, blank=True)

    terms_government_only = models.BooleanField(null=True)
    terms_pay_per_use = models.BooleanField(null=True)
    terms_uptime_guarantee = models.DecimalField(
        null=True,
        decimal_places=6,
        max_digits=8,
    )
    terms_support_response_time = models.PositiveIntegerField(
        help_text='Measured in number of workdays',
        null=True,
    )

    forum_vendor = models.CharField(max_length=MAX_ENUM_LENGTH, blank=True)
    forum_url = models.URLField(max_length=MAX_URL_LENGTH, blank=True)

    badges = models.ManyToManyField(
        'Badge',
        through='APIBadge',
        related_name='apis',
    )
    referenced_apis = models.ManyToManyField(
        'self',
        through='Relation',
        symmetrical=False,
        related_name='referenced_by_apis',
    )
    topics = models.ManyToManyField(Topic)

    def __str__(self):
        return self.api_id

    def get_absolute_url(self):
        return reverse("web:api_detail", kwargs={"api_id": self.api_id})

    def get_production_environment(self):
        return self.environments.filter(name=Environment.EnvironmentType.PRODUCTION).first()

    ADR_TESTABLE_TYPES = (APIType.REST_JSON.ODATA, APIType.REST_JSON, APIType.REST_XML)
    """API's of these types can be tested on API Design Rules"""

    def is_adr_testable(self):
        return self.api_type in self.ADR_TESTABLE_TYPES

    class BasicScore(NamedTuple):
        has_documentation: bool
        has_specification: bool
        has_contact_details: bool
        provides_sla: bool

    @cached_property
    def basic_api_score(self) -> "BasicScore":
        production_environment = self.get_production_environment()

        return self.BasicScore(
            has_documentation=(production_environment and production_environment.documentation_url != ""),
            has_specification=(production_environment and production_environment.specification_url != ""),
            has_contact_details=(self.contact_email != "" or self.contact_phone != "" or self.contact_url != ""),
            provides_sla=(self.terms_support_response_time is not None and self.terms_uptime_guarantee >= 0.9)
        )

    class Meta:
        verbose_name = _("API")
        verbose_name_plural = _("APIs")


class Environment(models.Model):
    class EnvironmentType(models.TextChoices):
        PRODUCTION = 'production', 'Production'
        ACCEPTANCE = 'acceptance', 'Acceptance'
        TEST = 'test', 'Test'
        DEMO = 'demo', 'Demo'

    name = models.CharField(max_length=MAX_ENUM_LENGTH, choices=EnvironmentType.choices)
    api_url = models.URLField(max_length=MAX_URL_LENGTH)
    specification_url = models.URLField(max_length=MAX_URL_LENGTH, blank=True)
    documentation_url = models.URLField(max_length=MAX_URL_LENGTH, blank=True)

    api = models.ForeignKey(
        API,
        to_field='api_id',
        on_delete=models.CASCADE,
        related_name='environments',
    )

    def __str__(self):
        return f"{self.name} - {self.api_url}"


class Relation(models.Model):
    TYPE_REFERENCE_IMPLEMENTATION = "reference-implementation"

    name = models.CharField(max_length=MAX_TEXT_LENGTH, blank=True)
    from_api = models.ForeignKey(
        API,
        to_field='api_id',
        on_delete=models.CASCADE,
        related_name='relations_from',
    )
    to_api = models.ForeignKey(
        API,
        to_field='api_id',
        on_delete=models.PROTECT,
        related_name='relations_to',
    )

    def __str__(self):
        return f'{self.from_api_id} {self.name} {self.to_api_id}'


class APIValidatorReport(BaseValidatorReport):
    api = ForeignValidatorReport(API)

core/models/topic.py
from django.db import models

from . import MAX_TEXT_LENGTH


class Topic(models.Model):
    name = models.CharField(max_length=MAX_TEXT_LENGTH, unique=True)

    def __str__(self):
        return self.name

web/views/contact.py
from django import forms
from django.urls import reverse_lazy
from django.views.generic import FormView
import yaml

from core import gitlab

from .generic import BaseView, TemplateView
from .mixins import Breadcrumb


class ContactForm(forms.Form):
    name = forms.CharField(max_length=100, required=False)
    email_address = forms.EmailField()
    subject = forms.CharField(max_length=100)
    message = forms.CharField(widget=forms.Textarea())

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.auto_id = "field_%s"

    def create_issue(self):
        title = self.cleaned_data["subject"]
        yaml_content = yaml.dump(self.cleaned_data, sort_keys=False)
        content = f"```yaml\n{yaml_content}\n````"

        gitlab.create_issue(title, content, "Contact form")


class ContactView(FormView, BaseView):
    title = "Neem contact met ons op"
    template_name = "contact.html"
    breadcrumb = Breadcrumb("contact", reverse_lazy("web:contact"))
    success_url = reverse_lazy("web:contact_success")
    form_class = ContactForm

    def form_valid(self, form: ContactForm):
        form.create_issue()
        return super().form_valid(form)

    def get_breadcrumbs(self):
        return [
            self.breadcrumb
        ]


class ContactSuccessView(TemplateView):
    title = "Versturen gelukt"
    template_name = "contact_success.html"
    breadcrumb = Breadcrumb("succes", reverse_lazy("web:contact_success"))
    
    def get_breadcrumbs(self):
        return [
            ContactView.breadcrumb,
            self.breadcrumb
        ]

web/views/statistics.py
from collections import defaultdict
from datetime import timedelta

from django.core.exceptions import BadRequest
from django.utils import dateformat, translation
from influxdb_client.client.flux_table import FluxRecord, TableList

from core import adr

from .generic import TemplateView
from ..statistics import get_statistics, serialize_design_rules_api_successes


class StatisticsView(TemplateView):
    template_name = "statistics.html"
    title = "Statistieken"

    time_ranges = {
        "laatste-maand": (-30, timedelta(days=1)),
        "laatste-jaar": (-365, timedelta(days=30)),
    }
    default_time_range = "laatste-maand"

    def get(self, request, *args, **kwargs):
        time_range_value = request.GET.get("periode")
        if time_range_value is None:
            time_range_value = self.default_time_range
        if time_range_value not in self.time_ranges:
            raise BadRequest(f"Invalid value for 'periode' parameter: {time_range_value}")

        self.time_range = time_range_value
        self.start_days, self.window_every = self.time_ranges[time_range_value]

        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        total_counts, api_design_rules_tables, design_rules_api_successes_last = (
            get_statistics(self.start_days, self.window_every))

        api_design_rules_per_rule = defaultdict(dict)
        for table in api_design_rules_tables:
            for record in table.records:
                name = record["rule"]
                api_design_rules_per_rule[name][record.get_field()] = int(record.get_value())

        def map_api_design_rules_per_rule():
            for name, fields in api_design_rules_per_rule.items():
                title, _ = adr.DESCRIPTION_MAPPING.get(name, ("", ""))
                percentage = int((fields["success_count"] / fields["total_count"]) * 100)
                yield name, title, percentage

        totals_labels, totals_series = _group_totals(total_counts)

        def get_totals(name):
            return {"labels": totals_labels[name], "series": totals_series[name]}

        context["time_range"] = self.time_range
        context["api_design_rules_per_rule"] = map_api_design_rules_per_rule
        context["graph_data"] = {
            "api-design-rules-per-score": serialize_design_rules_api_successes(design_rules_api_successes_last),
            "organization-totals": get_totals("organization"),
            "api-totals": get_totals("api"),
            "repository-totals": get_totals("repository"),
        }

        return context


def _group_totals(tables: TableList):
    labels = defaultdict(list)
    series = defaultdict(list)

    with translation.override(language="nl_NL"):
        for table in tables:
            record: FluxRecord
            for record in table.records:
                # In the frond-end the counts are displayed per day only.
                # So we're shifting the time of the metric with with 1 day and use only the date part.
                # This is tied to the Influx query because of the grouping per day.
                #
                # 2022-07-04 00:00:00+00:00 -> 2022-07-03
                date = (record.get_time() - timedelta(days=1)).date()

                labels[record.get_measurement()].append(dateformat.format(date, "j N"))
                series[record.get_measurement()].append(int(record.get_value()))

    return labels, series

web/templates/api_add_success.html
{% extends "layouts/base.html" %}
{% load static i18n don_extras %}

{% block content %}
<h1 class="mb-6">{{ title }}</h1>
<p class="font-size-lg">API is toegevoegd. Deze wordt zo snel mogelijk geplaatst.</p>
{% endblock %}

web/templates/api_detail.html
{% extends "layouts/base.html" %}
{% load static i18n don_extras %}

{% block content %}
    <div class="page-api-detail mb-md">
        <div class="api-top-content">
            <div class="title-row mb-xs">
                <h1 class="page-title mb-0">{{ title }}</h1>
                <span class="pill pill--white hide-upto-sm">{{ api.get_api_type_display }}</span>
            </div>
            <a href="{{ api.organization.get_absolute_url }}" class="page-subtitle mb-md">{{ api.organization.name }}</a>
            <p class="intro">{{ api.description }}</p>
            <span class="pill pill--white hide-from-sm">{{ api.get_api_type_display }}</span>
            <a class="button button--primary"
                target="_blank"
                href="https://gitlab.com/commonground/don/don-content/-/blob/main/content/api/{{ api.api_id }}.yaml"
                rel="noopener noreferrer"
                data-goatcounter-click="event:api-edit-content:{{ api.api_id }}"
                data-goatcounter-title="'Pas content aan' knop"
                data-goatcounter-referrer="{{ request.build_absolute_uri }}"
            >
                <svg class="button__icon" width="18" height="18" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z"></path>
                    <desc>
                        'Edit' icon by Reza Nur from The Nounproject
                    </desc>
                </svg>
                Pas content aan
            </a>
            <div class="api-topics">
                <p class="mt-4 mb-2 font-description-term">Thema's</p>
                {% if api.topics.all %}
                {% include "partials/topic_list.html" with topics=api.topics.all %}
                {% else %}
                <i>Geen thema's ingevuld.</i>
                {% endif %}
            </div>
        </div>
        <dl class="api-props vertical-sm mt-md mb-md">
            <div>
                <dt>API Authenticatie</dt>
                <dd>
                    {{ api.api_authentication | format_api_authentication }}
                </dd>
            </div>
            <div>
                <dt>Gebruik</dt>
                <dd>
                    {% if api.terms_government_only %}
                    Alleen overheid
                    {% else %}
                    Iedereen
                    {% endif %}
                </dd>
            </div>
            <div>
                <dt>Kosten</dt>
                <dd>
                    {% if api.terms_pay_per_use %}
                    Kosten voor gebruik
                    {% else %}
                    Gratis
                    {% endif %}
                </dd>
            </div>
            <div>
                <dt>Uptime garantie</dt>
                <dd>
                    {% if api.terms_uptime_guarantee %}
                    {% language "nl" %}
                    {{ api.terms_uptime_guarantee | floatformat:-2 }}{% endlanguage %}%
                    {% else %}
                    Geen
                    {% endif %}
                </dd>
            </div>
            <div>
                <dt>Helpdesk respons</dt>
                <dd>
                    {% if api.terms_support_response_time %}
                    {{ api.terms_support_response_time }}
                    werkdag{{ api.terms_support_response_time | pluralize:"en" }}
                    {% else %}
                    Geen
                    {% endif %}
                </dd>
            </div>
        </dl>
        <div class="environments card card--padding-md mb-md">
            <h2 class="card__title">Omgevingen</h2>
            {% for environment in api.environments.all %}
            <div class="environments__env">
                <h3>{{ environment.name }}</h3>
                <div class="environments__env__urls">
                    <code class="code">{{ environment.api_url }}</code>
                    {% if environment.specification_url %}
                    <a href="{% url 'web:api_specification' api.api_id environment.name %}"
                        class="button">Specificatie</a>
                    {% else %}
                    <span class="button button--disabled">Specificatie</span>
                    {% endif %}
                    {% if environment.documentation_url %}
                    <a href="{{ environment.documentation_url }}"
                        class="button button--external-link"
                        target="_blank"
                        rel="noopener noreferrer">Documentatie
                        <img src="{% static 'images/icons/external-link.svg' %}"
                            width="16"
                            height="16"
                            alt="">
                    </a>
                    {% else %}
                    <span class="button button--disabled">Documentatie</span>
                    {% endif %}
                </div>
            </div>
            {% endfor %}
        </div>
        {% if api.forum_url %}
        <div class="forum">
            <h2>Forum</h2>
            <a href="{{ api.forum_url }}"
                class="button button--external-link ml-4"
                target="_blank"
                rel="noopener noreferrer">Ga naar volledige forum
                <img src="{% static 'images/icons/external-link.svg' %}"
                    width="16"
                    height="16"
                    alt="">
            </a>
        </div>
        {% endif %}
        {% with repository_list=api.related_repositories.all %}
        {% if repository_list %}
        <div class="related-repositories card">
            <h2 class="card__title">Code</h2>
            <p>
                {{ repository_list | length }} open source
                {% if repository_list.count == 1 %}
                project gebruikt
                {% else %}
                projecten gebruiken
                {% endif %}
                deze API
            </p>
            <ul class="list-reset">
                {% for repository in repository_list %}
                {% repository_item repository %}
                {% endfor %}
            </ul>
        </div>
        {% endif %}
        {% endwith %}
        {% if implemented_by_api_list %}
        <div class="related-apis card card--padding-md mb-md">
            <h2 class="card__title">Geïmplementeerd door</h2>
            <ul class="list-reset">
                {% for api in implemented_by_api_list %}
                {% include "partials/api_item.html" with api=api cssClass="card" %}
                {% empty %}Er zijn momenteel geen API's die verwijzen naar deze referentie-implementatie.
                {% endfor %}
            </ul>
        </div>
        {% elif implemented_for_api_list %}
        <div class="related-apis card card--padding-md mb-md">
            <h2 class="card__title">
                Referentie implementatie{{ implemented_for_api_list | pluralize:"s" }}
            </h2>
            <ul class="list-reset">
                {% for api in implemented_for_api_list %}
                {% include "partials/api_item.html" with api=api %}
                {% endfor %}
                </ul>
                </div>
                {% endif %}
        {% if api.latest_validator_reports.count %}
        <h2 class="font-size-xl mt-0 mb-xs">API scores</h2>
        {% include "partials/validator_reports_summary.html" with validator_reports=api.latest_validator_reports %}
        <a href="{% url 'web:api_validator_reports' api_id=api.api_id %}" class="button button--primary mb-md align-self-end">
            API score details
            <svg class="button__icon button__icon--last button__icon--small-width ml-sm">
                <use xlink:href="{% static 'images/icons/tabler-sprite.svg' %}#tabler-chevron-right" />
            </svg>
        </a>
        {% endif %}
    </div>
{% endblock %}

web/templates/api_list.html
{% extends "layouts/base.html" %}
{% load static %}

{% block content %}
<h1 class="mb-5">{{ title }}</h1>
<p class="mb-0">Een wegwijzer naar de API's die (semi-)overheidsorganisaties in Nederland aanbieden.</p>
<div id="list-results" class="page-search">
    {% include "partials/api_list_results.html" %}
</div>
{% endblock %}

{% block tail %}
<script src="{% static 'dist/htmx.js' %}"></script>
{% endblock %}

web/templates/contact_success.html
{% extends "layouts/base.html" %}
{% load i18n %}

{% block content %}
<h1 class="mb-6">{{ title }}</h1>
<p class="font-size-lg">Bedankt voor je bericht! We gaan jouw vraag/ opmerking zo snel mogelijk behandelen. Omdat wij
    geen vaste redactie hebben kan dit tot enkele werkdagen duren.</p>
{% endblock %}

web/templates/index.html
{% extends "layouts/base.html" %}
{% load static don_extras %}

{% block content %}
<div class="page-homepage">
    <div class="hero py-xl">
        <div class="hero--bg">
            <img src="{% static 'images/hero_bg.webp' %}">
        </div>
        <div class="container">
            <div class="hero__intro">
                <h1 class="hero__intro__heading">Eén centrale plek voor de developer die voor of met de overheid
                    ontwikkelt</h1>
                <p class="hero__intro__subtitle">
                    Handige bronnen en de community
                    voor de ontwikkeling van jouw digitale services.
                </p>
            </div>
            <div class="hero__content">
                <a href="{% url 'web:api_list' %}" class="card card--primary card--call-to-action">
                    <svg width="60" height="60" class="card__icon">
                        <use xlink:href="{% static 'images/icons/tabler-sprite.svg' %}#tabler-affiliate" />
                    </svg>
                    <h2 class="mt-0 mb-xs">Vind een API</h2>
                    <p class="card__description">Bekijk welke API's er allemaal zijn en kom er achter hoe je jouw
                        oplossing hier op kan laten aansluiten.</p>
                    <div class="card__footer">
                        <svg class="card__footer__icon mr-3" width="16" height="17" viewBox="0 0 16 17" fill="none"
                            xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
                            <path
                                d="M6.67969 1.60547L7.45312 0.832031C7.80469 0.515625 8.33203 0.515625 8.64844 0.832031L15.5039 7.65234C15.8203 8.00391 15.8203 8.53125 15.5039 8.84766L8.64844 15.7031C8.33203 16.0195 7.80469 16.0195 7.45312 15.7031L6.67969 14.9297C6.36328 14.5781 6.36328 14.0508 6.67969 13.6992L10.9336 9.65625H0.84375C0.351562 9.65625 0 9.30469 0 8.8125V7.6875C0 7.23047 0.351562 6.84375 0.84375 6.84375H10.9336L6.67969 2.83594C6.36328 2.48438 6.32812 1.95703 6.67969 1.60547Z"
                                fill="white" />
                        </svg>
                        <span class="card__footer__text">Zoek API's</span>
                    </div>
                </a>
                <a href="{% url 'web:repository_list' %}"
                    class="card card--primary card--call-to-action">
                    <svg width="60" height="60" class="card__icon">
                        <use xlink:href="{% static 'images/icons/tabler-sprite.svg' %}#tabler-notebook" />
                    </svg>
                    <h2 class="mt-0 mb-xs">Vind een repository</h2>
                    <p class="card__description">Vind bestaande repository's om bij aan te haken en ontdek wat er binnen
                        welke organisatie beschikbaar is.</p>
                    <div class="card__footer">
                        <svg class="card__footer__icon mr-3" width="16" height="17" viewBox="0 0 16 17" fill="none"
                            xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
                            <path
                                d="M6.67969 1.60547L7.45312 0.832031C7.80469 0.515625 8.33203 0.515625 8.64844 0.832031L15.5039 7.65234C15.8203 8.00391 15.8203 8.53125 15.5039 8.84766L8.64844 15.7031C8.33203 16.0195 7.80469 16.0195 7.45312 15.7031L6.67969 14.9297C6.36328 14.5781 6.36328 14.0508 6.67969 13.6992L10.9336 9.65625H0.84375C0.351562 9.65625 0 9.30469 0 8.8125V7.6875C0 7.23047 0.351562 6.84375 0.84375 6.84375H10.9336L6.67969 2.83594C6.36328 2.48438 6.32812 1.95703 6.67969 1.60547Z"
                                fill="white" />
                        </svg>
                        <span class="card__footer__text">Zoek repository's</span>
                    </div>
                </a>
                <a href="{% url 'web:api_add' %}" class="card card--primary card--call-to-action">
                    <svg width="60" height="60" class="card__icon">
                        <use xlink:href="{% static 'images/icons/tabler-sprite.svg' %}#tabler-code-plus" />
                    </svg>
                    <h2 class="mt-0 mb-xs">API toevoegen</h2>
                    <p class="card__description">Voeg een overheids-API toe om deze beschikbaar te maken voor andere
                        developers.</p>
                    <div class="card__footer">
                        <svg class="card__footer__icon mr-3" width="16" height="17" viewBox="0 0 16 17" fill="none"
                            xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
                            <path
                                d="M6.67969 1.60547L7.45312 0.832031C7.80469 0.515625 8.33203 0.515625 8.64844 0.832031L15.5039 7.65234C15.8203 8.00391 15.8203 8.53125 15.5039 8.84766L8.64844 15.7031C8.33203 16.0195 7.80469 16.0195 7.45312 15.7031L6.67969 14.9297C6.36328 14.5781 6.36328 14.0508 6.67969 13.6992L10.9336 9.65625H0.84375C0.351562 9.65625 0 9.30469 0 8.8125V7.6875C0 7.23047 0.351562 6.84375 0.84375 6.84375H10.9336L6.67969 2.83594C6.36328 2.48438 6.32812 1.95703 6.67969 1.60547Z"
                                fill="white" />
                        </svg>
                        <span class="card__footer__text">Voeg jouw API toe</span>
                    </div>
                </a>
            </div>
        </div>
    </div>
    <div class="container page-homepage__leader-board py-xl">
        <h2 id="top-tien">Best scorende API's</h2>
        <div class="card card--padding-md">
            {% if api_validator_reports %}
            <ol class="api-score-list mt-0">
                {% for api_validator in api_validator_reports %}
                {% with api=api_validator.api report=api_validator.report %}
                <li>
                    <a href="{% url 'web:api_detail' api_id=api.api_id %}" class="api-score-list__item">
                        <div class="api-score-list__item__left">
                            <span class="api-score-list__item__left__counter">{{ forloop.counter }}</span>
                            <div class="api-score-list__item__left__text ml-4">
                                <p class="font-size-10 mb-0">{{ api.service_name | truncatechars:45 }}</p>
                                <p
                                    class="api-score-list__item__left__text__organisation text-color-palette-gray-700 mb-0">
                                    {{ api.organization.name | truncatechars:58 }}
                                </p>
                            </div>
                            <div class="api-score-list__item__left__text-mobile ml-4">
                                <p class="font-size-10 mb-0">{{ api.service_name | truncatechars:27 }}</p>
                                <p
                                    class="api-score-list__item__left__text__organisation text-color-palette-gray-700 mb-0">
                                    {{ api.organization.name | truncatechars:34 }}
                                </p>
                            </div>
                        </div>
                        <div class="api-score-list__item__pie">
                            {% score_pie report is_large=False %}
                        </div>
                    </a>
                </li>
                {% endwith %}
                {% endfor %}
            </ol>
            {% else %}
            <p>Er zijn op dit moment geen best scorende API's</p>
            {% endif %}
            <div class="card__body">
                <p>
                    Is je API geregistreerd, maar vind je deze niet terug in de top 10? Verbeter jouw API dan snel door
                    middel van
                    onze aanbevelingen.
                    Heb je jouw API nog helemaal niet geregistreerd? Druk dan op onderstaande knop om jouw API meteen
                    toe te voegen.
                </p>
                <a href="{% url 'web:api_add' %}" class="button button--add-icon">Voeg jouw API toe</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

web/templates/repository_list.html
{% extends "layouts/base.html" %}
{% load static %}

{% block content %}
<h1 class="mb-5">{{ title }}</h1>
<p class="mb-0">Overzicht van open source projecten van (semi-)overheidsorganisaties, of die hun API's gebruiken.</p>
<div id="list-results" class="page-search">
    {% include "partials/repository_list_results.html" %}
</div>
{% endblock %}

{% block tail %}
<script src="{% static 'dist/htmx.js' %}"></script>
{% endblock %}